# This is a basic workflow to help you get started with Actions

name: Container build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
     
      - name: Get image tag
        run: echo "GIT_TAG=`echo $(git describe --always --long --dirty)`" >> $GITHUB_ENV
     
      - name: Build container image
        uses: docker/build-push-action@v2.6.1
        with:
          push: true
          tags: ghcr.io/angusgyoung/waiter:${{ env.GIT_TAG }}
